title: Changjingxing Zhao's Homepage
page-top-title: Changjingxing Zhao
top-section-bg-text: Personal Website
home-subtitle: Changjingxing Zhao&ensp;|&ensp;赵常景行
programmes-subtitle: <i class="bi bi-inboxes-fill"></i>&nbsp;&nbsp;PROGRAMMES
skills-subtitle: <i class="bi bi-plus-square-fill"></i>&nbsp;&nbsp;SKILLS
awards-subtitle: <i class="bi bi-award-fill"></i>&nbsp;AWARDS
copyright-text: '&copy; Changjingxing Zhao 2025. All Rights Reserved.'
