title: Changjingxing Zhao's Homepage
page-top-title: Changjingxing Zhao
top-section-bg-text: Personal Website
home-subtitle: Changjingxing Zhao&ensp;|&ensp;赵常景行
programmes-subtitle: <i class="bi bi-inboxes-fill" aria-hidden="true"></i> PROGRAMMES
skills-subtitle: <i class="bi bi-plus-square-fill" aria-hidden="true"></i> SKILLS
awards-subtitle: <i class="bi bi-award-fill" aria-hidden="true"></i> AWARDS
copyright-text: '&copy; Changjingxing Zhao 2025. All Rights Reserved.'
